#!/bin/bash
domain=$(cat /etc/xray/domain)
IPVPS=$(curl -s ipv4.icanhazip.com)

function send_log(){
CHATID=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 3)
KEY=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 2)
TIME="10"
URL="https://api.telegram.org/bot$KEY/sendMessage"
TEXT="
<code>Script Auto Install by ABR Script Premium</code>
<code>──────────────────────────────</code>
<b>✨ USER MULTI LOGIN SSH/Dropbear ✨</b>
<code>──────────────────────────────</code>
<code>IP  : </code><code>$IPVPS</code>
<code>DOMAIN    : </code><code>$domain</code>
<code>──────────────────────────────</code>
<code>☞ $user $cekcek PID</code>
"
curl -s --max-time $TIME -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
}
function sship(){
#LIMITSSH
mulog=$(member)
data=( `ls /etc/kyt/limit/ssh/ip`);
#Decrypted By YADDY D PHREAKER
    for user in "${data[@]}"
do
iplimit=$(cat /etc/kyt/limit/ssh/ip/$user)
cekcek=$(echo -e "$mulog" | grep $user | wc -l);
if [[ $cekcek -gt $iplimit ]]; then
userdel -f $user
nais=3
echo -e "$waktu\nRemoved User: $user Login: $cekcek IP Max: $ip IP \n" >> /etc/kyt/log/ssh/ssh.log
else
echo > /dev/null
fi
sleep 30
done
if [[ $nais -gt 1 ]]; then
send_log
else
 echo ""
        fi
        sleep 0.1
